import type { CandidatePayload, SnapshotPayload } from "./types";

const now = Date.now() / 1000;

export const demoSnapshot: SnapshotPayload = {
  signals: [
    {
      code: "600392",
      name: "盛和资源",
      sector: "稀有金属",
      grade: "A",
      score: 91,
      price: 14.82,
      change_pct: 6.12,
      rise_1m_pct: 0.92,
      rise_3m_pct: 2.16,
      turnover_1m: 42_600_000,
      active_buy_ratio: 0.61,
      volume_spike: 2.8,
      order_book_bias: 0.18,
      signal_age_sec: 8,
      quality_tags: ["高位维持", "买盘强"],
      reasons: ["主线龙头放量", "主动买入占优", "板块共振"],
      sparkline: [14.22, 14.28, 14.31, 14.36, 14.42, 14.55, 14.66, 14.82],
    },
    {
      code: "603158",
      name: "腾龙股份",
      sector: "汽车零部件",
      grade: "B",
      score: 76,
      price: 15.18,
      change_pct: 3.84,
      rise_1m_pct: 0.48,
      rise_3m_pct: 1.36,
      turnover_1m: 18_900_000,
      active_buy_ratio: 0.56,
      volume_spike: 2.1,
      order_book_bias: 0.11,
      signal_age_sec: 18,
      quality_tags: ["震荡推升"],
      reasons: ["前排助攻放量", "主买占优"],
      sparkline: [14.72, 14.76, 14.81, 14.86, 14.93, 15.02, 15.09, 15.18],
    },
    {
      code: "002600",
      name: "领益智造",
      sector: "消费电子",
      grade: "B",
      score: 73,
      price: 8.46,
      change_pct: 2.79,
      rise_1m_pct: 0.36,
      rise_3m_pct: 0.88,
      turnover_1m: 65_400_000,
      active_buy_ratio: 0.53,
      volume_spike: 1.9,
      order_book_bias: 0.09,
      signal_age_sec: 24,
      quality_tags: ["容量承接"],
      reasons: ["容量中军放量", "承接稳定"],
      sparkline: [8.22, 8.25, 8.28, 8.31, 8.34, 8.39, 8.42, 8.46],
    },
    {
      code: "002624",
      name: "完美世界",
      sector: "游戏",
      grade: "C",
      score: 66,
      price: 14.58,
      change_pct: 2.18,
      rise_1m_pct: 0.31,
      rise_3m_pct: 0.76,
      turnover_1m: 11_800_000,
      active_buy_ratio: 0.52,
      volume_spike: 1.6,
      order_book_bias: 0.06,
      signal_age_sec: 31,
      quality_tags: ["低位补涨"],
      reasons: ["主线补涨试盘", "主买略占优"],
      sparkline: [14.23, 14.25, 14.29, 14.34, 14.38, 14.43, 14.51, 14.58],
    },
    {
      code: "605151",
      name: "西上海",
      sector: "汽车零部件",
      grade: "B",
      score: 72,
      price: 23.23,
      change_pct: 4.41,
      rise_1m_pct: 1.12,
      rise_3m_pct: 1.95,
      turnover_1m: 22_100_000,
      active_buy_ratio: 0.49,
      volume_spike: 2.5,
      order_book_bias: 0.04,
      signal_age_sec: 12,
      quality_tags: ["后排跟风"],
      reasons: ["涨速达标", "但非主线前排"],
      sparkline: [22.42, 22.55, 22.78, 22.92, 23.03, 23.16, 23.2, 23.23],
    },
  ],
  new_signals: [],
  tracked_alerts: [
    {
      code: "600392",
      name: "盛和资源",
      grade: "A",
      age_sec: 260,
      trigger_price: 14.45,
      current_price: 14.82,
      current_return_pct: 2.56,
      max_return_pct: 3.02,
      min_return_pct: -0.28,
    },
    {
      code: "603158",
      name: "腾龙股份",
      grade: "B",
      age_sec: 180,
      trigger_price: 14.96,
      current_price: 15.18,
      current_return_pct: 1.47,
      max_return_pct: 1.68,
      min_return_pct: -0.12,
    },
  ],
  sector_heat: {
    稀有金属: 7,
    汽车零部件: 5,
    消费电子: 4,
    游戏: 3,
  },
  performance: {
    total: 2,
    positive_rate: 100,
    by_grade: {},
  },
  runtime: {
    status: "demo",
    source: "leader-demo",
    data_age_sec: 0,
    tick_count: 4280,
    batch_count: 86,
    session: {
      code: "demo",
      label: "明日模拟",
      is_live: false,
      time: "09:43:20",
      date: "2026-05-26",
    },
  },
};

export const demoCandidates: CandidatePayload = {
  candidates: [
    {
      code: "600392",
      name: "盛和资源",
      sector: "稀有金属",
      board: "main",
      price: 14.82,
      prev_close: 13.97,
      change_pct: 6.12,
      rise_speed_pct: 0.92,
      min2_amount: 88_000_000,
      active_buy_ratio: 0.61,
      turnover_rate: 8.2,
      candidate_score: 126,
      adjusted_score: 138,
      quality_level: "strong",
      quality_label: "核心龙头",
      explanation: "市场最高标继续放量，稀有金属主线强度保持，等换手承接不破均价。",
      candidate_reasons: ["4板高度", "主线龙头", "封单强", "主买占优"],
      risk_flags: ["高位博弈"],
      market_mood: "主升试错",
      theme_rank: 1,
      hot_money_role: "精盯龙头",
      leader_role: "市场总龙头",
      leader_score: 612,
      market_height_rank: 1,
      theme_leader_rank: 1,
      limit_up: true,
      limit_up_streak: 4,
      first_limit_time: "09:41",
      seal_amount: 420_000_000,
      distance_to_limit_pct: 3.88,
      buy_pattern: "高标换手确认",
      top_status: "active",
      top_age_sec: 1710,
    },
    {
      code: "603158",
      name: "腾龙股份",
      sector: "汽车零部件",
      board: "main",
      price: 15.18,
      prev_close: 14.62,
      change_pct: 3.84,
      rise_speed_pct: 0.48,
      min2_amount: 31_000_000,
      active_buy_ratio: 0.56,
      turnover_rate: 5.1,
      candidate_score: 96,
      adjusted_score: 104,
      quality_level: "strong",
      quality_label: "前排助攻",
      explanation: "汽车零部件分支前排，放量温和，适合等站稳均价后再处理。",
      candidate_reasons: ["2板梯队", "题材前排", "放量温和"],
      risk_flags: [],
      market_mood: "主升试错",
      theme_rank: 2,
      hot_money_role: "题材前排",
      leader_role: "前排助攻",
      leader_score: 328,
      market_height_rank: 5,
      theme_leader_rank: 2,
      limit_up: false,
      limit_up_streak: 2,
      first_limit_time: "10:08",
      distance_to_limit_pct: 6.16,
      buy_pattern: "前排分歧转强",
      top_status: "candidate",
    },
    {
      code: "002600",
      name: "领益智造",
      sector: "消费电子",
      board: "main",
      price: 8.46,
      prev_close: 8.23,
      change_pct: 2.79,
      rise_speed_pct: 0.36,
      min2_amount: 92_000_000,
      active_buy_ratio: 0.53,
      turnover_rate: 3.7,
      candidate_score: 88,
      adjusted_score: 97,
      quality_level: "strong",
      quality_label: "容量中军",
      explanation: "主线容量中军，成交额足够，适合做承接观察，不做追高。",
      candidate_reasons: ["容量承接", "成交额放大", "趋势中军"],
      risk_flags: ["弹性一般"],
      market_mood: "主升试错",
      theme_rank: 3,
      hot_money_role: "趋势中军",
      leader_role: "容量中军",
      leader_score: 286,
      market_height_rank: 9,
      theme_leader_rank: 1,
      buy_pattern: "中军放量站稳",
      top_status: "candidate",
    },
    {
      code: "002624",
      name: "完美世界",
      sector: "游戏",
      board: "main",
      price: 14.58,
      prev_close: 14.27,
      change_pct: 2.18,
      rise_speed_pct: 0.31,
      min2_amount: 16_000_000,
      active_buy_ratio: 0.52,
      turnover_rate: 2.9,
      candidate_score: 74,
      adjusted_score: 83,
      quality_level: "watch",
      quality_label: "补涨候选",
      explanation: "游戏分支不是最高强度，只能作为主线补涨观察，必须放量后再考虑。",
      candidate_reasons: ["主线补涨", "低位弹性"],
      risk_flags: ["非核心龙头"],
      market_mood: "主升试错",
      theme_rank: 3,
      hot_money_role: "补涨候选",
      leader_role: "补涨候选",
      leader_score: 162,
      market_height_rank: 14,
      theme_leader_rank: 2,
      buy_pattern: "低位补涨试盘",
      top_status: "candidate",
    },
    {
      code: "605151",
      name: "西上海",
      sector: "汽车零部件",
      board: "main",
      price: 23.23,
      change_pct: 4.41,
      rise_speed_pct: 1.12,
      min2_amount: 22_100_000,
      active_buy_ratio: 0.49,
      candidate_score: 64,
      adjusted_score: 54,
      quality_level: "caution",
      quality_label: "后排跟风",
      explanation: "虽然涨速快，但不是分支前排，主买不够强，当前系统应过滤。",
      candidate_reasons: ["涨速达标"],
      risk_flags: ["后排跟风", "主买不足"],
      market_mood: "主升试错",
      theme_rank: 8,
      hot_money_role: "后排跟风",
      leader_role: "后排跟风",
      leader_score: 78,
      buy_pattern: "过滤样本",
      top_status: "candidate",
    },
  ],
  sector_heat: [
    { sector: "稀有金属", count: 7, active_top: 2 },
    { sector: "汽车零部件", count: 5, active_top: 1 },
    { sector: "消费电子", count: 4, active_top: 1 },
    { sector: "游戏", count: 3, active_top: 0 },
  ],
  hot_money: {
    mood: "主升试错",
    emotion_score: 76,
    strong_count: 3,
    high_count: 4,
    active_top: 2,
  },
  leader_pool: {
    date: "2026-05-26",
    limit_pool_count: 42,
    market_height: 4,
    emotion: {
      cycle: "主升试错",
      score: 76,
      action: "只做主线前排和最高标",
      position: "半仓以内",
      mode: "leader",
      fail_rate: 14,
      open_board_count: 6,
      high_count: 4,
      second_count: 8,
      early_count: 16,
      mainline: "稀有金属",
      reason: "高度4板，主线涨停扩散，炸板率可控。",
    },
    height_leaders: [
      { code: "600392", name: "盛和资源", sector: "稀有金属", limit_up_streak: 4, first_limit_time: "09:41", seal_amount: 420_000_000 },
      { code: "603158", name: "腾龙股份", sector: "汽车零部件", limit_up_streak: 2, first_limit_time: "10:08", seal_amount: 160_000_000 },
    ],
    leaders: [
      { code: "600392", name: "盛和资源", sector: "稀有金属", leader_role: "市场总龙头", limit_up_streak: 4, leader_score: 612 },
      { code: "603158", name: "腾龙股份", sector: "汽车零部件", leader_role: "前排助攻", limit_up_streak: 2, leader_score: 328 },
      { code: "002600", name: "领益智造", sector: "消费电子", leader_role: "容量中军", limit_up_streak: 0, leader_score: 286 },
    ],
    limit_themes: [
      {
        sector: "稀有金属",
        limit_count: 7,
        max_height: 4,
        early_count: 4,
        open_board_count: 1,
        seal_amount: 920_000_000,
        score: 156,
        leader: { code: "600392", name: "盛和资源", limit_up_streak: 4, first_limit_time: "09:41" },
        stocks: [
          { code: "600392", name: "盛和资源", limit_up_streak: 4, first_limit_time: "09:41", role: "龙头" },
        ],
      },
      {
        sector: "汽车零部件",
        limit_count: 5,
        max_height: 2,
        early_count: 2,
        open_board_count: 2,
        seal_amount: 360_000_000,
        score: 118,
        leader: { code: "603158", name: "腾龙股份", limit_up_streak: 2, first_limit_time: "10:08" },
        stocks: [
          { code: "603158", name: "腾龙股份", limit_up_streak: 2, first_limit_time: "10:08", role: "前排" },
          { code: "605151", name: "西上海", limit_up_streak: 0, first_limit_time: "", role: "后排" },
        ],
      },
      {
        sector: "消费电子",
        limit_count: 4,
        max_height: 1,
        early_count: 2,
        open_board_count: 1,
        seal_amount: 280_000_000,
        score: 96,
        leader: { code: "002600", name: "领益智造", limit_up_streak: 0, first_limit_time: "" },
        stocks: [
          { code: "002600", name: "领益智造", limit_up_streak: 0, role: "中军" },
        ],
      },
    ],
  },
  health: {
    source: "demo",
    filtered_count: 1,
    sector_heat: [
      { sector: "稀有金属", count: 7, active_top: 2 },
      { sector: "汽车零部件", count: 5, active_top: 1 },
      { sector: "消费电子", count: 4, active_top: 1 },
      { sector: "游戏", count: 3, active_top: 0 },
    ],
    filtered_reasons: {
      后排跟风: 1,
    },
  },
};

export function isDemoMode(): boolean {
  return new URLSearchParams(window.location.search).get("demo") === "leader";
}

export function demoTime(): string {
  return new Date(now * 1000).toLocaleTimeString("zh-CN", { hour12: false });
}
